-- AlterTable
ALTER TABLE "MT5Account" ADD COLUMN IF NOT EXISTS "balance" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "MT5Account" ADD COLUMN IF NOT EXISTS "credit" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "MT5Account" ADD COLUMN IF NOT EXISTS "equity" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "MT5Account" ADD COLUMN IF NOT EXISTS "group" TEXT;
ALTER TABLE "MT5Account" ADD COLUMN IF NOT EXISTS "isEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "MT5Account" ADD COLUMN IF NOT EXISTS "leverage" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "MT5Account" ADD COLUMN IF NOT EXISTS "margin" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "MT5Account" ADD COLUMN IF NOT EXISTS "marginFree" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "MT5Account" ADD COLUMN IF NOT EXISTS "marginLevel" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "MT5Account" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "MT5Account" ADD COLUMN IF NOT EXISTS "platform" TEXT;
ALTER TABLE "MT5Account" ADD COLUMN IF NOT EXISTS "profit" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "MT5Account" ADD COLUMN IF NOT EXISTS "status" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "MT5Account" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
